{% set name = "cite" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cite-{{ version }}.tar.gz
  sha256: 047bfe815f2bd26dbb8740a518dcb326368c79a0304d5571ab99211a676b426f

build:
  number: 0
  noarch: python
  entry_points:
    - cite=cite:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - python >=3.6
    - python-slugify
    - requests

test:
  commands:
    - pip check
    - cite --help
  requires:
    - pip

about:
  home: https://github.com/rgieseke/cite
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Command line tool to get bibliography e.g. BibTex entries'
  description: |
    Prints citation from DOIs or URLs of journal articles which 
    provide DOIs in their metadata.
  doc_url: https://github.com/rgieseke/cite
  dev_url: https://github.com/rgieseke/cite

extra:
  recipe-maintainers:
    - jan-janssen
